site_name: Compliant Kubernetes
site_url: https://compliantkubernetes.io
site_description: >-
  Compliant Kubernetes is a Kubernetes distribution that reduces the burden
  for complying with HIPAA, Swedish Healthcare (Patientdatalagen), GDPR and
  ISO 27001.
site_author: Elastisys AB
copyright: Copyright © 2020 Elastisys AB

repo_url: https://github.com/elastisys/compliantkubernetes

google_analytics:
  - UA-68368435-4
  - auto

theme:
  name: material
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Overview: 'index.md'
  - 'Compliance Basics': 'compliance.md'
  - 'Core Concepts': 'concepts.md'
  - 'Getting Started': 'getting-started.md'
  - 'User Guide':
    - 'Overview': 'user-guide/index.md'
    - 'Container Registry (Harbor)': 'user-guide/harbor.md'
    - 'Kubernetes API': 'user-guide/kubernetes-api.md'
    - 'Elasticsearch/Kibana': 'user-guide/elasticsearch.md'
    - 'Prometheus/Grafana': 'user-guide/prometheus.md'
    - 'Dashboard': 'user-guide/dashboard.md'
  - 'Operator Manual':
    - 'Overview': 'operator-manual/index.md'
    - 'Getting Started': 'operator-manual/getting-started.md'
    - 'Creating/Destroying/Upgrading a Cluster': 'operator-manual/lifecycle.md'
    - 'Configuring a Cluster': 'operator-manual/configuring.md'
    - 'Breaking the Glass': 'operator-manual/break-glass.md'
  - 'FAQ': 'faq.md'
  - 'Roadmap': 'roadmap.md'
  - 'Support ⧉': 'https://compliantkubernetes.com/'
  - 'Blog ⧉': 'https://elastisys.com/blog/'
