name: deploy

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          pwd
          ls -l
          id -u
          id -g
          pip3 install mkdocs
          mkdocs gh-deploy
